---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp1
  namespace: apps
spec:
  serviceAccountName: default
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: cont1
          image: suryarelangi/pyimg:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: svc1
  namespace: apps
spec:
  type: loadBalancer
  selector:
    app: web
  ports:
    - port: 8000
      targetPort: 8000  
